version: '3'

services:
  website:
    build: ./ 
    
    ports:
      - 80:5000
    container_name: website
    depends_on:
      - sandbox
    image: brad314/website
    
  sandbox:
    build: ./coderunner
    
    container_name: sandbox
    image: brad314/sandbox
    
      
