version: '3'

services:
  website:
    build: ./ 

    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:5000
    container_name: website
    depends_on:
      - sandbox
    image: brad314/website
    
  sandbox:
    build: ./coderunner
    volumes:
      - /coderunner/fileStorage
    container_name: sandbox
    image: brad314/sandbox
    
      
