version: '3'

services:
  website:
    build: ./ 

    depends_on:
      # - proxy
      - db

    environment:
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://coderunner:app@db/app
    
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/brad/coderunner/coderunner
      - /home/brad/coderunner/migrations
    ports:
      - 80:5000
    container_name: website
    image: brad314/website
    
  sandbox:
    build: ./coderunner
    
    volumes:
      - /coderunner/fileStorage
    container_name: sandbox
    image: brad314/sandbox
  
  db:
    image: postgres:latest

    environment:
      POSTGRES_USER: brad
      POSTGRES_PASSWORD: coderunner
      POSTGRES_DB: app

    restart: always
    ports:
      - 5405:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  # proxy:      
  #     image: nginx:latest
  #     hostname: proxy
  #     ports:
  #       - 80:80
  #       - 443:443
        
  #     volumes:
  #       - /home/brad/coderunner/config:/etc/nginx
  #       - /home/brad/coderuneer/certs:/etc/ssl/private
        