version: '3'

services:
  website:
    build: ./ 
    
    volumes: 
      - ./coderunner
    
    ports:
      - 5000:80
    container_name: website
    depends_on:
      - sandbox
    image: brad314/website
    memory: 512
  sandbox:
    build: ./coderunner
    
    container_name: sandbox
    image: brad314/sandbox
    memory: 512
      